
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:

    prefer-ip-address: true

spring:
  application:
    name: provider
management:
  endpoints:
    web:
      exposure:
       include: "beans,env,trace,info"

info:
  app.name: provider-server
  company.name: companyName
  build.artifactId: provider
  build.version: 0.0.1-SNAPSHOT

---

spring:
  profiles: pro1
server:
  port: 8081

---

spring:
  profiles: pro2
server:
  port: 8083

